server:
  port: 9001

spring:
  application:
    name: user-service

eureka:
  client:
    # eureka에 등록된 인스턴스들의 정보 갱신 여부 설정
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
