server:
  port: 0

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/msa?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: gang6607
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-init-sql: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: UTC
        show_sql: true
        format_sql: true

greeting:
  message: Welcome to the Simple E-commerce


logging:
  level:
    inflern.study.userservice: DEBUG

token:
  expiration:
    time:
      ms: 3600000
  secret: 2cadded2582bbb92b7b6f9e56b66626481135cd1bfb20540a9afcdd7decde3881a611d1b8b7d0c883c1354b83a734b846cd1e2bafafcdb65b25d112708939747