server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: git
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/study/config_native/spring_cloud_msa
        git:
          uri: https://github.com/HanGyulKang/spring-cloud-config
