server:
  port: 8761

spring:
  application:
    name: discoveryservice

eureka:
  client:
    register-with-eureka: false # 기본값(True)로 설정 시 자기 자신을 유레카 서비스에 등록하려고 하기 때문에,
    fetch-registry: false       # 불필요한 등록을 피하려고 False로 방어조치 한다.
